### ISSUE TITLE
Deluge download broken since last update

### ISSUE THREAD

**Issue by albatros69** [pymedusa/Medusa#6368]
**Describe the bug**
Since the very last update, torrents are not added to deluge, with an import error message. Likely related to 5418ce6 

**To Reproduce**
Just trying to download something via deluged triggers the error.

**Expected behavior**
the download should be added to deluged as prior to the update

**Medusa (please complete the following information):**
- OS: Debian 9
- Branch: master
- Commit:  94fae84
- Python Version: 2.7.13

**Logs:**
```
SNATCHQUEUE-SNATCH-295647 :: [94fae84] Snatch failed! For result: <...>
Traceback (most recent call last):
  File "/home/deploy/Medusa/medusa/search/queue.py", line 503, in run
    self.success = snatch_episode(result)
  File "/home/deploy/Medusa/medusa/search/core.py", line 166, in snatch_episode
    client = torrent.get_client_class(app.TORRENT_METHOD)()
  File "/home/deploy/Medusa/medusa/clients/torrent/__init__.py", line 47, in get_client_class
    return get_client_module(name).api
  File "/home/deploy/Medusa/medusa/clients/torrent/__init__.py", line 36, in get_client_module
    return __import__('{prefix}.{name}'.format(prefix=__name__, name=name.lower()), fromlist=_clients)
  File "/home/deploy/Medusa/medusa/clients/torrent/deluged.py", line 15, in <module>
    from deluge_client import DelugeRPCClient
ImportError: cannot import name DelugeRPCClient
```

**Comment by DrAndri** [comment]
I'm having the same exact problem, seems to have started when I updated to v0.3.0

OS: ubuntu 16.04
Branch: master

**Comment by medariox** [comment]
Remove the `.pyc` files in the medusa/clients folder and its subdirectories or switch to Python 3.

**Comment by p0psicles** [comment]
stop medusa
go into the medusa/clients folder
run: `find . -name *.pyc -exec rm {} \;`
start medusa

**Comment by DrAndri** [comment]
I ran the command with quotes around *.pyc:
`find . -name "*.pyc" -exec rm {} \;`
else it wouldn't remove the files recursively

Thanks for your help!

**Comment by albatros69** [comment]
Excellent, that indeed did the trick!
Thanks
