### ISSUE TITLE
Blank screen issue since updating to 0.5.7

### ISSUE THREAD

**Issue by ragepaw-git** [pymedusa/Medusa#9196]
**Describe the bug**
I have 2 deployments, since updating Feb 11th, both cannot load shows. The issue is identical.

Docker:
Branch: master
Commit: 279292a40a6861d40f0cbedea5d8971a274b0ae5
Version: 0.5.7
Database: 44.17
Python Version:  3.7.6 (default, Dec 21 2019, 02:28:04) [GCC 8.3.0]
SSL Version: OpenSSL 1.1.1d 10 Sep 2019
OS: Linux-5.4.72-microsoft-standard-WSL2-x86_64-with
Locale: en_US.UTF-8

Error:
2021-02-11 08:41:42 ERROR    Thread_7 :: [279292a] Exception generated: displayShow() got an unexpected keyword argument 'indexername'
Traceback (most recent call last):
  File "/app/medusa/medusa/server/web/core/base.py", line 252, in async_call
    result = function(**kwargs)
TypeError: displayShow() got an unexpected keyword argument 'indexername'

Windows
Branch: master
Commit: 279292a40a6861d40f0cbedea5d8971a274b0ae5
Version: 0.5.7
Database: 44.17
Python Version:  3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
SSL Version: OpenSSL 1.1.0j 20 Nov 2018
OS: Windows-10-10.0.19041-SP0
Locale: en_CA.cp1252

Error
2021-02-11 08:41:15 ERROR    Thread_58 :: [279292a] Exception generated: displayShow() got an unexpected keyword argument 'indexername'
Traceback (most recent call last):
  File "C:\Medusa\Medusa\medusa\server\web\core\base.py", line 252, in async_call
    result = function(**kwargs)
TypeError: displayShow() got an unexpected keyword argument 'indexername'
2021-02-11 08:41:10 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [DrunkenSlug] :: [279292a] DailySearchQueueItem Exception, error: GuessitException('An internal error has occured in guessit.\n===================== Guessit Exception Report =====================\nversion=3.3.1\nstring=[DAiRY] The SoulTaker - Tamashii-gari Ep 9 (US DVDEncode)\noptions={\'expected_title\': 
{I parsed out a bunch of show specific items here}
\n--------------------------------------------------------------------\nTraceback (most recent call last):\n  File "C:\\Medusa\\Medusa\\ext\\guessit\\api.py", line 192, in guessit\n    matches = self.rebulk.matches(string, options)\n  File "C:\\Medusa\\Medusa\\ext\\rebulk\\rebulk.py", line 115, in matches\n    self._execute_rules(matches, context)\n  File "C:\\Medusa\\Medusa\\ext\\rebulk\\rebulk.py", line 146, in _execute_rules\n    rules.execute_all_rules(matches, context)\n  File "C:\\Medusa\\Medusa\\ext\\rebulk\\rules.py", line 312, in execute_all_rules\n    when_response = execute_rule(rule, matches, context)\n  File "C:\\Medusa\\Medusa\\ext\\rebulk\\rules.py", line 333, in execute_rule\n    when_response = rule.when(matches, context)\n  File "C:\\Medusa\\Medusa\\medusa\\name_parser\\rules\\rules.py", line 675, in when\n    unique_eps = set([ep.initiator.value.lower() for ep in episodes])\n  File "C:\\Medusa\\Medusa\\medusa\\name_parser\\rules\\rules.py", line 675, in <listcomp>\n    unique_eps = set([ep.initiator.value.lower() for ep in episodes])\nAttributeError: \'int\' object has no attribute \'lower\'\n--------------------------------------------------------------------\nPlease report at https://github.com/guessit-io/guessit/issues.\n====================================================================')
Traceback (most recent call last):
  File "C:\Medusa\Medusa\ext\guessit\api.py", line 192, in guessit
    matches = self.rebulk.matches(string, options)
  File "C:\Medusa\Medusa\ext\rebulk\rebulk.py", line 115, in matches
    self._execute_rules(matches, context)
  File "C:\Medusa\Medusa\ext\rebulk\rebulk.py", line 146, in _execute_rules
    rules.execute_all_rules(matches, context)
  File "C:\Medusa\Medusa\ext\rebulk\rules.py", line 312, in execute_all_rules
    when_response = execute_rule(rule, matches, context)
  File "C:\Medusa\Medusa\ext\rebulk\rules.py", line 333, in execute_rule
    when_response = rule.when(matches, context)
  File "C:\Medusa\Medusa\medusa\name_parser\rules\rules.py", line 675, in when
    unique_eps = set([ep.initiator.value.lower() for ep in episodes])
  File "C:\Medusa\Medusa\medusa\name_parser\rules\rules.py", line 675, in <listcomp>
    unique_eps = set([ep.initiator.value.lower() for ep in episodes])
AttributeError: 'int' object has no attribute 'lower'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Medusa\Medusa\medusa\search\queue.py", line 295, in run
    found_results = search_for_needed_episodes(self.scheduler_start_time, force=self.force)
  File "C:\Medusa\Medusa\medusa\search\core.py", line 526, in search_for_needed_episodes
    cur_provider.cache.update_cache(scheduler_start_time)
  File "C:\Medusa\Medusa\medusa\tv\cache.py", line 245, in update_cache
    parsed_result = NameParser().parse(item['title'])
  File "C:\Medusa\Medusa\medusa\name_parser\parser.py", line 400, in parse
    result = self._parse_string(name)
  File "C:\Medusa\Medusa\medusa\name_parser\parser.py", line 304, in _parse_string
    guess = guessit.guessit(name, dict(show_type=self.show_type))
  File "C:\Medusa\Medusa\medusa\name_parser\guessit_parser.py", line 86, in guessit
    result = default_api.guessit(name, options=final_options)
  File "C:\Medusa\Medusa\ext\guessit\api.py", line 208, in guessit
    raise GuessitException(string, options) from err
guessit.api.GuessitException: An internal error has occured in guessit.
===================== Guessit Exception Report =====================
version=3.3.1
string=[DAiRY] The SoulTaker - Tamashii-gari Ep 9 (US DVDEncode)
options={'expected_title': [
I parsed out show specific items here]
}
--------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Medusa\Medusa\ext\guessit\api.py", line 192, in guessit
    matches = self.rebulk.matches(string, options)
  File "C:\Medusa\Medusa\ext\rebulk\rebulk.py", line 115, in matches
    self._execute_rules(matches, context)
  File "C:\Medusa\Medusa\ext\rebulk\rebulk.py", line 146, in _execute_rules
    rules.execute_all_rules(matches, context)
  File "C:\Medusa\Medusa\ext\rebulk\rules.py", line 312, in execute_all_rules
    when_response = execute_rule(rule, matches, context)
  File "C:\Medusa\Medusa\ext\rebulk\rules.py", line 333, in execute_rule
    when_response = rule.when(matches, context)
  File "C:\Medusa\Medusa\medusa\name_parser\rules\rules.py", line 675, in when
    unique_eps = set([ep.initiator.value.lower() for ep in episodes])
  File "C:\Medusa\Medusa\medusa\name_parser\rules\rules.py", line 675, in <listcomp>
    unique_eps = set([ep.initiator.value.lower() for ep in episodes])
AttributeError: 'int' object has no attribute 'lower'
--------------------------------------------------------------------
Please report at https://github.com/guessit-io/guessit/issues.
====================================================================

**To Reproduce**
1. Open any show from the main page

**Expected behavior**
The show will display

**Comment by medariox** [comment]
Fixed with version 0.5.8
