### ISSUE TITLE
Error running 1.0.1

### ISSUE THREAD

**Issue by bluelavalamp** [pymedusa/Medusa#10694]
I just downloaded 1.0.1 and tried running but I get this error:

Traceback (most recent call last):
  File "/opt/Medusa-master/./start.py", line 6, in <module>
    from medusa.__main__ import main
  File "/opt/Medusa-master/medusa/__init__.py", line 24, in <module>
    initialize()
  File "/opt/Medusa-master/medusa/init/__init__.py", line 37, in initialize
    _configure_guessit()
  File "/opt/Medusa-master/medusa/init/__init__.py", line 202, in _configure_guessit
    from medusa.name_parser.guessit_parser import (
  File "/opt/Medusa-master/medusa/name_parser/guessit_parser.py", line 12, in <module>
    from medusa.logger.adapters.style import BraceAdapter
  File "/opt/Medusa-master/medusa/logger/__init__.py", line 44, in <module>
    import knowit
  File "/opt/Medusa-master/ext/knowit/__init__.py", line 19, in <module>
    from knowit.api import KnowitException, know
  File "/opt/Medusa-master/ext/knowit/api.py", line 7, in <module>
    from knowit.provider import Provider
  File "/opt/Medusa-master/ext/knowit/provider.py", line 8, in <module>
    from knowit.properties import Quantity
  File "/opt/Medusa-master/ext/knowit/properties/__init__.py", line 18, in <module>
    from knowit.properties.video import (
ImportError: cannot import name 'VideoDimensions' from 'knowit.properties.video' (/opt/Medusa-master/ext/knowit/properties/video/__init__.py)

Python version is 3.9.9.  I've been running Medusa for a couple years now and this is the first time I've gotten this error.

Thanks

**Comment by p0psicles** [comment]
we suspect that it still has references to the files from medusa version 1.0.0.
Would you be able to run a bash script?

**Comment by p0psicles** [comment]
If that doesn't work run these:
https://github.com/pymedusa/Medusa/issues/10692#issuecomment-1142415340

**Comment by ebogaard** [comment]
Same problem here after upgrade to 1.0.0, then to 1.0.1. But this on el8 with python 3.6.8.
Checked with the find & grep command, no hits.

**Comment by p0psicles** [comment]
Can you easily upgrade to python 3.10?

**Comment by medariox** [comment]
The problem is that you have still old files in the `medusa/ext/` folder, suggesting your upgrade didn't complete correctly. What you can do is deleting the medusa/ext folder and replace it with the ext folder from master. Alternatively you can rest the install with git fetch origin && git reset --hard origin/master as p0psicles suggested.

**Comment by ebogaard** [comment]
Usually I use the in-app upgrade procedure, so I might have missed something. So I removed the ext-folders, and put the ones from the v1.0.1 package in place. This leads to the following issue:
```
 Traceback (most recent call last):
   File "/home/ebogaard/Medusa/ext/pymediainfo/__init__.py", line 16, in <module>
     from importlib import metadata
 ImportError: cannot import name 'metadata'
 During handling of the above exception, another exception occurred:
 Traceback (most recent call last):
   File "/home/ebogaard/Medusa/ext/importlib_metadata/_compat.py", line 9, in <module>
     from typing import Protocol
 ImportError: cannot import name 'Protocol'
 During handling of the above exception, another exception occurred:
 Traceback (most recent call last):
   File "/home/ebogaard/Medusa/start.py", line 6, in <module>
     from medusa.__main__ import main
   File "/home/ebogaard/Medusa/medusa/__init__.py", line 24, in <module>
     initialize()
   File "/home/ebogaard/Medusa/medusa/init/__init__.py", line 37, in initialize
     _configure_guessit()
   File "/home/ebogaard/Medusa/medusa/init/__init__.py", line 202, in _configure_guessit
     from medusa.name_parser.guessit_parser import (
   File "/home/ebogaard/Medusa/medusa/name_parser/guessit_parser.py", line 12, in <module>
     from medusa.logger.adapters.style import BraceAdapter
   File "/home/ebogaard/Medusa/medusa/logger/__init__.py", line 44, in <module>
     import knowit
   File "/home/ebogaard/Medusa/ext/knowit/__init__.py", line 19, in <module>
     from knowit.api import KnowitException, know
   File "/home/ebogaard/Medusa/ext/knowit/api.py", line 8, in <module>
     from .providers import (
   File "/home/ebogaard/Medusa/ext/knowit/providers/__init__.py", line 5, in <module>
     from knowit.providers.mediainfo import MediaInfoProvider
   File "/home/ebogaard/Medusa/ext/knowit/providers/mediainfo.py", line 9, in <module>
     from pymediainfo import MediaInfo
   File "/home/ebogaard/Medusa/ext/pymediainfo/__init__.py", line 18, in <module>
     import importlib_metadata as metadata  # type: ignore
   File "/home/ebogaard/Medusa/ext/importlib_metadata/__init__.py", line 17, in <module>
     from . import _adapters, _meta
   File "/home/ebogaard/Medusa/ext/importlib_metadata/_meta.py", line 1, in <module>
     from ._compat import Protocol
   File "/home/ebogaard/Medusa/ext/importlib_metadata/_compat.py", line 11, in <module>
     from typing_extensions import Protocol  # type: ignore
   File "/home/ebogaard/Medusa/ext/typing_extensions.py", line 159, in <module>
     class _FinalForm(typing._SpecialForm, _root=True):
 AttributeError: module 'typing' has no attribute '_SpecialForm'
```

**Comment by ebogaard** [comment]
If I use 3.9.7 (=python39 package in el8), then Medusa starts as expected.
So it's an issue with 3.6.8 .

**Comment by bluelavalamp** [comment]
> The problem is that you still have old files in the `medusa/ext/` folder, suggesting your upgrade didn't complete correctly. What you can do is deleting the `medusa/ext` folder and replace it with the `ext` folder from master (just download it from GitHub and replace only that one folder). Alternatively you can reset the install with `git fetch origin` and `git reset --hard origin/master` as p0psicles suggested.

This fixed the issue!  Thank you

**Comment by p0psicles** [comment]
Version 1.0.2 is out specifically for python 3.6 users.

**Comment by ebogaard** [comment]
I just tested 1.0.2 with python 3.6.
After deleting ext/__pycache__/*, I can start Medusa as expected. So this issue seems fixed.

**Comment by medariox** [comment]
Awesome, thanks for confirming!

**Comment by p0psicles** [comment]
Keeping issue open for others

**Comment by mbarland** [comment]
> > The problem is that you still have old files in the `medusa/ext/` folder, suggesting your upgrade didn't complete correctly. What you can do is deleting the `medusa/ext` folder and replace it with the `ext` folder from master (just download it from GitHub and replace only that one folder). Alternatively you can reset the install with `git fetch origin` and `git reset --hard origin/master` as p0psicles suggested.
> 
> This fixed the issue! Thank you

Fixed it for me as well. Python 3.6.9 on Ubuntu 18.04.

**Comment by jappish84** [comment]
> The problem is that you still have old files in the `medusa/ext/` folder, suggesting your upgrade didn't complete correctly. What you can do is deleting the `medusa/ext` folder and replace it with the `ext` folder from master (just download it from GitHub and replace only that one folder). Alternatively you can reset the install with `git fetch origin` and `git reset --hard origin/master` as p0psicles suggested.

Fixed for me aswell!
Dietpi 8.5.1

**Comment by medariox** [comment]
Closing as it's pinned.
